name: CI

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    container: mrothy/scalafmt-native
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt test
        run: --test /src
  test:
    name: Scala
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-scala-2.13-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-scala-2.13-
      - name: test
        run: sbt test
