name: CI

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt
        uses: openlawteam/scalafmt-ci@v2
        with:
          args: "--exclude=third_party --list"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-scala-
      - name: test
        run: sbt test
