name: CI

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt
        uses: openlawteam/scalafmt-ci@v2
        with:
          args: "--exclude=third_party --list"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - name: Cache SBT ivy2 cache # https://github.com/actions/cache/blob/master/examples.md#scala---sbt
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy2-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy2-cache-${{ hashFiles('**/build.sbt') }}
            ${{ runner.os }}-sbt-ivy2-cache-
      - name: Cache SBT couriser cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}
            ${{ runner.os }}-sbt-coursier-cache-
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-${{ hashFiles('**/build.sbt') }}
            ${{ runner.os }}-sbt-cache-
      - name: test
        run: sbt test
