name: CI

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  format:
    name: Scalafmt Action
    uses: openlawteam/scalafmt-ci@v2.0.2
  test:
    name: Scala
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-scala-
      - name: test
        run: sbt test
